"use strict";
exports.__esModule = true;
exports.CastAttribute = exports.ModelDecorator = exports.Collection = exports.Cast = exports.Relation = exports.BaseEntity = void 0;
var BaseEntity_1 = require("./BaseEntity");
exports.BaseEntity = BaseEntity_1.BaseEntity;
var Decorators_1 = require("./Decorators");
exports.Cast = Decorators_1.Cast;
exports.Relation = Decorators_1.Relation;
exports.Collection = Decorators_1.Collection;
exports.ModelDecorator = Decorators_1.ModelDecorator;
var CastAttribute_1 = require("./Casts/CastAttribute");
exports.CastAttribute = CastAttribute_1.CastAttribute;
